services:
  nginx:
    container_name : nginx-demo
    image : nginx:latest

    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`nginx.docker.localhost`)
      - traefik.http.routers.nginx.entrypoints=web

    networks:
      - proxy

networks:
  proxy:
    external: true